# Generated by Django 4.0.3 on 2022-03-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('rasm', models.FileField(upload_to='bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Ichki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('rasm', models.FileField(upload_to='ichki')),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.FileField(upload_to='mahsulot')),
                ('tasdiq', models.CharField(default='Tasdiqlangan', max_length=30)),
                ('narx', models.IntegerField()),
                ('batafsil', models.TextField()),
                ('aksiya', models.PositiveSmallIntegerField(default=0)),
                ('brend', models.CharField(max_length=50)),
                ('kafolat', models.CharField(max_length=20)),
                ('yetkazish', models.CharField(max_length=20)),
                ('mavjud', models.BooleanField(default=True)),
                ('ichki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.ichki')),
                ('mijoz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.PositiveSmallIntegerField()),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulot_baholari', to='asosiy.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.mijoz')),
            ],
        ),
    ]
