# Generated by Django 4.0.3 on 2022-03-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_ichki_bolim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='ichki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ichki_mahsulotlar', to='asosiy.ichki'),
        ),
    ]
