# Generated by Django 4.0.3 on 2022-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_mahsulot_mamlakat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='promoted',
            field=models.BooleanField(default=True),
        ),
    ]
