# Generated by Django 4.0.3 on 2022-03-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asosiy', '0001_initial'),
        ('userapp', '0002_manzil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.PositiveSmallIntegerField(default=1)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('yetkazish_puli', models.IntegerField()),
                ('summa', models.IntegerField()),
                ('status', models.CharField(default='Jarayonda', max_length=15)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.mijoz')),
                ('savat', models.ManyToManyField(to='buyurtma.savat')),
            ],
        ),
    ]
