# Generated by Django 4.0.3 on 2022-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0006_alter_buyurtma_savat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='yetkazish_puli',
            field=models.IntegerField(default=15000),
        ),
    ]
