# Generated by Django 4.0.3 on 2022-03-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamlakat', models.CharField(max_length=30)),
                ('shahar', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=7)),
                ('default', models.BooleanField(blank=True)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.mijoz')),
            ],
        ),
    ]
