# Generated by Django 4.0.3 on 2022-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_manzil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='tel',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
